import JSZip from 'jszip';

/* Save the live project as a JSON file (browser download) and return the
 * filename. The schema is intentionally simple so a user can re-import the
 * file into the app on a different machine.
 */
export function saveProject(project) {
  const payload = {
    schema: 'gwn-project/v1',
    title: project.title || 'untitled',
    prompt: project.prompt || '',
    savedAt: new Date().toISOString(),
    files: project.files || {},
  };
  const json = JSON.stringify(payload, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  a.href = url;
  a.download = `${slug(project.title || 'gwn-project')}-${stamp}.gwn.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  return a.download;
}

/* Bundle the live project files into a ZIP and trigger a browser download.
 * Returns the filename.
 */
export async function downloadZip(files, title) {
  const zip = new JSZip();
  const names = Object.keys(files || {});
  if (names.length === 0) throw new Error('Nothing to download — generate a project first.');

  for (const name of names) {
    zip.file(name, files[name] || '');
  }
  // Minimal README so the user can find their way around after extraction.
  const readme = [
    `# ${title}`,
    '',
    `Generated by OmniOne Agent Harness.`,
    `Open ${names.find((n) => /\.html?$/i.test(n)) || names[0]} in any browser.`,
    '',
    '## Files',
    ...names.map((n) => `- \`${n}\``),
  ].join('\n');
  zip.file('README.md', readme);

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  a.href = url;
  a.download = `${slug(title)}-${stamp}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  return a.download;
}

function slug(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 40) || 'gwn-project';
}
